version: '3.3'

services:
  backend:
    image: rubenzagon/randybackend
    restart: always
    container_name: "randy_backend"
    environment:
      - NODE_ENV=production
      - PORT=8080
    ports:
      - 8080:8080
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: "randy_db"
    restart: always
    volumes:
      - ./db/mongodb/:/etc/mongo
