version: '3.1'

services:
  db:
    build: "./mariadb/"
    image: "randy/mariadb:1.0"
    container_name: "randy_mariadb"
    restart: always
    volumes:
      - ${PWD}/dbrandyapp:/var/lib/mysql
  node:
    image: randy/randy:latest
    restart: always

